In [1]:
import torch 
import torch.nn as nn 




In [ ]:
# Shape of Conv Layers 
N, n_H, n_W, n_C = 1, 28, 28, 3
n_filter =3
k_size = 3


image = torch.randn(size=(N, n_C, n_H, n_W))
print(image.size())

torch.Size([1, 3, 28, 28])


In [ ]:
conv = nn.Conv2d(in_channels=n_filter, out_channels=1, kernel_size=k_size)
y = conv(image)

In [ ]:
weight, bias = conv.weight, conv.bias
print(image.size())
print(weight.size())
print(bias.size())
print(y.size())

torch.Size([1, 3, 28, 28])
torch.Size([1, 3, 3, 3])
torch.Size([1])
torch.Size([1, 1, 26, 26])


In [ ]:
# Correlation Calculation
import numpy as np
N, n_H, n_W, n_C = 1, 28, 28, 1
n_filter =1
k_size = 3


image = torch.randn(size=(N, n_C, n_H, n_W))

conv = nn.Conv2d(in_channels=n_filter, out_channels=1, kernel_size=k_size)
y = conv(image)
weight, bias = conv.weight, conv.bias
print('='*100)

image = image.detach().numpy().squeeze()
weight = weight.squeeze()
# print(image.size())
# print(weight.size())
# print(bias.size())


y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))


for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = image[i: i+k_size, j: j+k_size]
    y_man[i, j] = np.sum(window * weight) + bias


y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))

# Convolution 3D 
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = image[i: i+k_size, j: j+k_size, :]
    y_man[i, j] = np.sum(window * weight) + bias



TypeError: ignored

In [ ]:
np.sum(window*weight)  + bias

TypeError: ignored

In [ ]:
weight

tensor([[ 0.3006, -0.0023, -0.2662],
        [ 0.0010, -0.1189, -0.1564],
        [ 0.0517, -0.1756, -0.0786]], grad_fn=<SqueezeBackward0>)

In [ ]:
N, n_H, n_W, n_C  = 1, 28, 28, 3
n_filters = 5
f_size = 3 



image = torch.randn(size=(N, n_C, n_H, n_W))

conv = nn.Conv2d(in_channels=3, out_channels=n_filters, kernel_size=f_size)

Y = conv(image)
Weight, bias = conv.weight, conv.bias


# batch size, channel height width
print(f'input image: {image.size()}')
# 하나의 images는 RGB 값을 가지고 있어서 channel 3  window size는 3 x 3  filter가 5개 있다는것 그래서 weight가 5개 bias도 5개 
# 하나의 filter가 window연산을 하면 하나의 이미지가 만들어지고 filter개수만큼 만들어져서 output 이미지가 5개 만들어짐 
print(f'weight size: {Weight.size()}')
print(f'bias size: {bias.size()}')

input image: torch.Size([1, 3, 28, 28])
weight size: torch.Size([5, 3, 3, 3])
bias size: torch.Size([5])


In [ ]:
Y.size()

torch.Size([1, 5, 26, 26])

In [ ]:
import numpy as np 


images = np.random.randint(low= 0, high = 10, size=(2, 3, 4))


for channels in range(4):
  print(images[:, :, channels])
  print()

[[8 1 1]
 [5 4 5]]

[[1 8 3]
 [2 6 1]]

[[2 3 4]
 [7 4 1]]

[[4 6 5]
 [6 9 0]]



In [ ]:
print(images.shape)

(2, 3, 4)


In [ ]:
tmp = np.transpose(images, (2, 0, 1))

In [ ]:
print(tmp)
print(tmp.shape)

[[[8 1 1]
  [5 4 5]]

 [[1 8 3]
  [2 6 1]]

 [[2 3 4]
  [7 4 1]]

 [[4 6 5]
  [6 9 0]]]
(4, 2, 3)


In [ ]:
Y = Y.squeeze()
Y

tensor([[[ 3.8465e-01,  1.9009e-01, -7.4577e-01,  ...,  6.1484e-01,
           2.9538e-01,  3.6092e-01],
         [ 5.3302e-01, -1.0114e-01,  8.5029e-02,  ...,  8.7546e-03,
           2.8648e-01,  9.1867e-01],
         [ 4.6788e-01,  6.8170e-01, -9.7468e-02,  ..., -2.8355e-01,
          -8.2757e-02, -4.4487e-01],
         ...,
         [ 6.7559e-01,  6.5664e-01, -1.8166e-01,  ...,  1.6426e+00,
           5.7614e-01, -1.2676e-01],
         [-4.4924e-01,  4.3097e-01,  3.1516e-01,  ..., -9.5056e-01,
          -2.6204e-01, -2.2001e-01],
         [ 2.2722e-01,  3.9659e-01,  1.5697e-01,  ...,  3.9483e-01,
          -2.6087e-01,  7.7254e-02]],

        [[-9.4928e-01, -4.1667e-01, -1.4818e-01,  ...,  2.1191e-01,
          -3.2635e-01,  1.0897e-01],
         [ 8.3394e-01,  2.5598e-01,  6.4301e-01,  ...,  7.7956e-02,
           5.3415e-02, -2.2255e-01],
         [-1.5370e-01, -1.1422e-01, -7.8854e-01,  ..., -4.9980e-01,
           1.3124e-01, -4.7795e-01],
         ...,
         [ 7.8428e-01,  1

In [ ]:
for c in range(26):
  print(Y[:, :, c])
  print()

tensor([[ 3.8465e-01,  5.3302e-01,  4.6788e-01, -1.1431e+00,  7.7994e-01,
          2.1195e-01,  1.1675e-01, -4.3336e-01,  6.0680e-01, -1.1149e+00,
         -1.3355e-02,  4.5484e-01,  1.5154e-01,  8.7207e-01,  3.8714e-02,
          9.4942e-01,  3.7088e-01, -1.9812e-01, -5.5419e-01,  2.3845e-01,
         -3.5121e-01,  5.4571e-01,  7.4000e-01,  6.7559e-01, -4.4924e-01,
          2.2722e-01],
        [-9.4928e-01,  8.3394e-01, -1.5370e-01,  3.4895e-01,  1.7145e-01,
          1.3648e-02, -4.1360e-01, -3.6462e-01,  5.4777e-01, -3.0844e-01,
          1.2264e-01, -4.3810e-01,  8.7074e-01, -2.9995e-01, -1.0019e+00,
          1.4587e-01, -5.6889e-01, -9.3919e-02, -7.1096e-01, -6.6093e-01,
          2.0958e-01,  9.7599e-01, -2.4260e-01,  7.8428e-01, -4.3120e-01,
          7.3402e-04],
        [ 1.1327e-01, -7.9515e-01, -7.4253e-03,  8.7818e-02, -8.4854e-02,
          3.8546e-03, -6.2358e-01, -1.2922e+00, -2.5934e-01,  8.2761e-02,
          1.1723e-01,  5.7763e-01,  6.6240e-02,  2.5197e-01, -1.10

In [ ]:
Y.shape

torch.Size([5, 26, 26])

In [ ]:
n, nh,nw,nc = 1, 5, 5, 3 
n_filter = 3
k_size= 4 


# batch_size, channel, height, width 
images = torch.randn(size=(n, nc, nh,nw))
convv = nn.Conv2d(in_channels=nc, out_channels=n_filter, kernel_size=k_size)
y = convv(images)

c_weight, c_bias = convv.weight, convv.bias

# 5 x 5인 RGB 값을 가진 이미지가 Convolution에 들어갔다. 그래서 conv의 weight와 bias를 해석해보자면, 4 x 4 window와 3개의 필터가 각각 연산이 되어 총 3개의 이미지가 뽑히는것이다.
# 그래서 y의 shape를 보면 한장의 이미지가 나오는데 1장의 이미지의 rgb값 3개 연산되어 나왔고 2x2사이즈로 줄어들었다. 
print('images shape: ', images.size())
print('weight shape: ', c_weight.size())
print('bias shape: ', c_bias.size())
print('y shape: ', y.size())

yy = y.squeeze()
print(yy.shape)
Y_man = np.zeros(shape=(nh - k_size + 1, nw - k_size + 1, n_filter))
print(Y_man.shape)


images = images.squeeze()
images = np.transpose(images, (2,1, 0))
print(images.shape)
for c in range(n_filter):
  c_W = c_weight[:, c, :]
  c_W = c_W.detach().numpy()
  c_W = np.transpose(c_W, (2, 1, 0))
  print(c_W.shape)
  c_B = c_bias[c]

  for h in range(nh - k_size + 1):
    for j in range(nw - k_size + 1):
      window = images[h:h+k_size, j:j+k_size, :]
      window = window.detach().numpy()
      con_plus = np.sum(c_W*window) + c_B
      # print('Weight shape: ', c_W.shape, 'window shape: ', window.shape)
      Y_man[h,j, c] =  con_plus

images shape:  torch.Size([1, 3, 5, 5])
weight shape:  torch.Size([3, 3, 4, 4])
bias shape:  torch.Size([3])
y shape:  torch.Size([1, 3, 2, 2])
torch.Size([3, 2, 2])
(2, 2, 3)
torch.Size([5, 5, 3])
(4, 4, 3)
(4, 4, 3)
(4, 4, 3)


In [ ]:
yy

tensor([[[-0.4761, -0.3055],
         [-0.6643, -0.0072]],

        [[ 0.9818, -0.2326],
         [-0.6566, -0.7214]],

        [[-0.2713, -0.4692],
         [ 0.8902, -0.0020]]], grad_fn=<SqueezeBackward0>)

In [ ]:
Y_man = np.transpose(Y_man, (2, 1, 0))
Y_man

array([[[-0.49340436, -0.17360453],
        [ 0.36388439,  1.03298163]],

       [[-0.13732612, -0.73025692],
        [-0.42648199,  0.00645007]],

       [[-0.58123946,  0.29610723],
        [ 0.38325116,  0.53781754]]])

In [ ]:
#model with Conv Layers 

n_neurons = [10,20, 30]


model = nn.Sequential(
    nn.Conv2d(in_channels=3, out_channels=n_neurons[0], kernel_size=3),
    nn.ReLU(),
    nn.Conv2d(in_channels=n_neurons[0], out_channels=n_neurons[1], kernel_size=3),
    nn.ReLU(),
    nn.Conv2d(in_channels=n_neurons[1], out_channels=n_neurons[2], kernel_size=3)
)

x = torch.randn(size = (32, 3, 28, 28))

y = model(x)
print(f'input size: {x.size()}')
print(f'output size: {y.size()}')

input size: torch.Size([32, 3, 28, 28])
output size: torch.Size([32, 30, 22, 22])


In [ ]:
class Testmodel(nn.Module):
  def __init__(self):
    super(Testmodel, self).__init__()


    n_neurons = [10,20, 30]
    self.conv = nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=n_neurons[0], kernel_size=3),
        nn.ReLU(),
        nn.Conv2d(in_channels=n_neurons[0], out_channels=n_neurons[1], kernel_size=3),
        nn.ReLU(),
        nn.Conv2d(in_channels=n_neurons[1], out_channels=n_neurons[2], kernel_size=3)    
    )


  def forward(self, x):
    print(self.conv[0])
    conv1_weight, conv1_bias = self.conv[0].weight, self.conv[0].bias
    print('Conv1 layer shape: ',conv1_weight.size(), conv1_bias.size())
    print()
    print('Conv2 layer shape:', self.conv[2])
    conv2_weight, conv2_bias = self.conv[2].weight, self.conv[2].bias
    print('Conv1 layer shape: ',conv2_weight.size(), conv2_bias.size())
    print()

    print('Conv2 layer shape:', self.conv[4])
    conv3_weight, conv3_bias = self.conv[4].weight, self.conv[4].bias
    print('Conv1 layer shape: ',conv3_weight.size(), conv3_bias.size())
    output = self.conv(x)

    return output 



In [ ]:
models = Testmodel()

In [ ]:
x.shape

torch.Size([32, 3, 28, 28])

In [ ]:

yy1 =models(x)

Conv2d(3, 10, kernel_size=(3, 3), stride=(1, 1))
Conv1 layer shape:  torch.Size([10, 3, 3, 3]) torch.Size([10])

Conv2 layer shape: Conv2d(10, 20, kernel_size=(3, 3), stride=(1, 1))
Conv1 layer shape:  torch.Size([20, 10, 3, 3]) torch.Size([20])

Conv2 layer shape: Conv2d(20, 30, kernel_size=(3, 3), stride=(1, 1))
Conv1 layer shape:  torch.Size([30, 20, 3, 3]) torch.Size([30])


In [ ]:

yy1.size()

torch.Size([32, 30, 22, 22])

In [ ]:
yy1[:, 1, :, :].size()

torch.Size([32, 22, 22])

In [ ]:
import pandas as pd 

pd.DataFrame(yy1[:, 1, :, :][0]).columns

RangeIndex(start=0, stop=22, step=1)

In [ ]:
print(len(pd.DataFrame(yy1[:, 1, :, :][0])))

22


In [ ]:
for c in range(30):

  imagea = yy1[:, c, :, :]
  print(imagea)
  print()

tensor([[[-0.0720, -0.0739, -0.0250,  ...,  0.0658,  0.0962, -0.0604],
         [-0.0689,  0.0040, -0.0481,  ..., -0.0270,  0.1155,  0.0174],
         [-0.0270,  0.0139, -0.0704,  ...,  0.0703, -0.0058,  0.0087],
         ...,
         [ 0.0328,  0.0176,  0.0774,  ...,  0.0665,  0.1715,  0.0417],
         [ 0.0309, -0.1030,  0.0219,  ...,  0.0895,  0.1557,  0.0762],
         [ 0.0862, -0.0080,  0.0692,  ..., -0.0020,  0.0324,  0.0046]],

        [[ 0.0574,  0.0245,  0.1256,  ...,  0.0492,  0.1018,  0.0497],
         [ 0.1077,  0.0617,  0.1264,  ...,  0.0554, -0.1080,  0.1418],
         [ 0.0937,  0.0510,  0.0016,  ...,  0.0466, -0.0687,  0.1308],
         ...,
         [-0.0021,  0.0943,  0.0231,  ..., -0.0196, -0.0137,  0.0183],
         [ 0.0767, -0.0406, -0.1230,  ...,  0.0540,  0.0269,  0.0642],
         [ 0.0430, -0.0489, -0.0757,  ...,  0.0421, -0.0261,  0.1197]],

        [[-0.0103, -0.0514, -0.0504,  ...,  0.0588,  0.0312,  0.0431],
         [-0.0781, -0.0132,  0.0291,  ..., -0

In [20]:
# Max Pooling 
import numpy as np

L, f, s  = 10, 2, 1 


x = torch.randn(size=(1, 1, 10))
print(x.size())
pooled_max = nn.MaxPool1d(kernel_size=f, stride=s)
pooledd_max =pooled_max(x)


print('x: {}\n{}'.format(x.size(), x.numpy().flatten()))

print('pooled_max(Pytorch): {}\n{}'.format(pooledd_max.size(), pooledd_max.numpy().flatten()))




## window을 한 이미지에서 돌아다니면서 max값을 가져오는 방법
xx = x.numpy().flatten()

print()
poool_man = np.zeros(shape=(L - f + 1))

for i in range(L - f + 1):
  windows = xx[i:i+f]
  print(windows)
  poool_man[i] = np.max(windows)


print(f'poool_man shape: {poool_man.shape}, poool_man: {poool_man}')


torch.Size([1, 1, 10])
x: torch.Size([1, 1, 10])
[ 0.4136631  -0.15069611  0.18267567 -0.03786691  0.16222827  0.0905129
  0.24812296  0.3212363   0.43755287 -2.4221187 ]
pooled_max(Pytorch): torch.Size([1, 1, 9])
[0.4136631  0.18267567 0.18267567 0.16222827 0.16222827 0.24812296
 0.3212363  0.43755287 0.43755287]

[ 0.4136631  -0.15069611]
[-0.15069611  0.18267567]
[ 0.18267567 -0.03786691]
[-0.03786691  0.16222827]
[0.16222827 0.0905129 ]
[0.0905129  0.24812296]
[0.24812296 0.3212363 ]
[0.3212363  0.43755287]
[ 0.43755287 -2.4221187 ]


In [28]:

# Average Pooling 
L, f, s = 10, 2, 1

# batchsize, channel, datas
x1 = torch.randn(size=(1, 1, L))

pool_avg = nn.AvgPool1d(kernel_size = f, stride=s)
pooled_avg = pool_avg(x1)

print(f'x shape: {x1.size()}\nx: {x1}')
print(f'Average Poold_1D: {pooled_avg}\nAverage Poold1D shape:{pooled_avg.size()}')



x1 = x1.numpy().flatten()


avg_pool = np.zeros(shape=(L-f + 1))


for channel in range(L-f+1):
  wind = x1[channel: channel+f]

  avg_pool[channel] = np.mean(wind)
print(f'numpy avg pool: {avg_pool} numpy shape: {avg_pool.shape}')

x shape: torch.Size([1, 1, 10])
x: tensor([[[-0.6760,  0.8584, -0.3458, -0.3361,  0.1879, -1.0312,  0.4693,
           1.4797, -0.9802,  0.5415]]])
Average Poold_1D: tensor([[[ 0.0912,  0.2563, -0.3409, -0.0741, -0.4216, -0.2810,  0.9745,
           0.2497, -0.2194]]])
Average Poold1D shape:torch.Size([1, 1, 9])
numpy avg pool: [ 0.09118274  0.25628337 -0.34094656 -0.07407653 -0.42163756 -0.28095031
  0.97446221  0.24972379 -0.21937186] numpy shape: (9,)


In [33]:

# Max Pooling 2D 

N, n_H, n_W, C = 1, 5, 5, 1
f, s = 2, 1

x2 = torch.randn(size=(N, C, n_H, n_W))
print(x2.size())



pool_max = nn.MaxPool2d(kernel_size=2, stride=1)
pooled_max = pool_max(x2)


print(f'x2 shape: {x2.size()}, x2: {x2}')
print(f'maxpool 2D: {pooled_max}, maxpool 2D shape:{pooled_max.shape}')

torch.Size([1, 1, 5, 5])
x2 shape: torch.Size([1, 1, 5, 5]), x2: tensor([[[[ 0.3049,  0.8579,  1.7252,  1.0747,  0.9191],
          [ 0.1303,  1.3866, -0.3825,  2.1281,  0.0625],
          [ 1.2142, -0.3279, -1.0926, -1.0547,  0.0523],
          [-0.6211,  0.2358,  0.4933, -0.4781, -3.0971],
          [ 1.0280, -0.7970, -0.4670, -0.6311,  0.7941]]]])
maxpool 2D: tensor([[[[1.3866, 1.7252, 2.1281, 2.1281],
          [1.3866, 1.3866, 2.1281, 2.1281],
          [1.2142, 0.4933, 0.4933, 0.0523],
          [1.0280, 0.4933, 0.4933, 0.7941]]]]), maxpool 2D shape:torch.Size([1, 1, 4, 4])


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


In [54]:
# Max Pooling row - level 
x2_sqze = x2.detach().numpy().squeeze()
print(x2_sqze.shape)


pools2d = np.zeros(shape=(n_H - f + 1, n_W -f + 1))


for i in range(n_H - f +1):
  for j in range(n_W -f +1):

    windows = x2_sqze[i:i+f, j:j+f]
    maxss = np.max(windows)
    pools2d[i, j] = maxss


print(f'numpy get 2D : {pools2d}, 2D shape: {pools2d.shape}')

(5, 5)
numpy get 2D : [[1.38663304 1.72516751 2.12806439 2.12806439]
 [1.38663304 1.38663304 2.12806439 2.12806439]
 [1.21419215 0.49331224 0.49331224 0.05226273]
 [1.02795684 0.49331224 0.49331224 0.79408175]], 2D shape: (4, 4)


In [43]:
x2_sqze[0, :3]

tensor([0.3049, 0.8579, 1.7252])

In [55]:
# Average Pooling 2D low - level
x2_sqze = x2.detach().numpy().squeeze()
print(x2_sqze.shape)


pools2d = np.zeros(shape=(n_H - f + 1, n_W -f + 1))


for i in range(n_H - f +1):
  for j in range(n_W -f +1):

    windows = x2_sqze[i:i+f, j:j+f]
    maxss = np.mean(windows)
    pools2d[i, j] = maxss


print(f'numpy get 2D : {pools2d}, 2D shape: {pools2d.shape}')

(5, 5)
numpy get 2D : [[ 0.66993642  0.89680266  1.13637495  1.04611373]
 [ 0.60081714 -0.10408762 -0.10042682  0.29704544]
 [ 0.12525412 -0.17285249 -0.53302979 -1.14441836]
 [-0.03858957 -0.13372377 -0.27072564 -0.853073  ]], 2D shape: (4, 4)
