In [11]:
import torch 
import torch.nn as nn
import numpy as np 
import math 

In [23]:
# Maxpooling 3D
N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2,2 




x = torch.randn(size=(N, n_C, n_H, n_W))
print(x.size())

# window가 지나가면서 max pool가 되고 각 채널별로 뽑히게 된다. 그래서 채널은 그대로 height와 width은 변한다. 
pool_max = nn.MaxPool2d(kernel_size=f, stride=s)
pooled_max = pool_max(x)
print(pooled_max.size())
print(pooled_max)


xx = x.detach().numpy().squeeze()
xx = np.transpose(xx, (2, 1, 0))

print(xx.shape)

n_H_ = math.floor((n_H - f)/s+1)
n_W_ = math.floor((n_W - f)/s+1)
print(n_H_, n_W_)


pooled_max_man = np.zeros(shape= (n_H_, n_W_, n_C))
print(pooled_max_man)


for c in range(n_C):
  c_images = xx[:, :, c]

  h_ = 0
  for h in range(0,n_H -f + 1, s):
    w_ = 0 
    for w in range(0, n_W -f + 1, s):
      window = c_images[h:h+f, w:w+f]
      pooled_max_man[h_,w_, c] = np.max(window)

      w_ +=1
    h_ +=1
print(pooled_max_man.shape)
print(pooled_max_man)

torch.Size([1, 3, 5, 5])
torch.Size([1, 3, 2, 2])
tensor([[[[ 0.5603,  2.0305],
          [ 0.7270,  2.0706]],

         [[ 0.9009, -0.0725],
          [ 1.4069,  0.9977]],

         [[ 1.0503,  1.9462],
          [ 0.6662,  1.0333]]]])
(5, 5, 3)
2 2
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
[[[ 0.56031829  0.9009096   1.05030894]
  [ 0.72703975  1.4069382   0.66618925]]

 [[ 2.03048992 -0.07249386  1.94618213]
  [ 2.07064176  0.9976995   1.03330564]]]


In [31]:
zero_images = torch.randn(size=(1, 3, 3, 3))
print(zero_images.size())


zero_padding = nn.ZeroPad2d(padding=2)
zeroed_padding = zero_padding(zero_images)
print(zeroed_padding)

torch.Size([1, 3, 3, 3])
tensor([[[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000, -0.6530, -0.4210,  0.5642,  0.0000,  0.0000],
          [ 0.0000,  0.0000, -1.5979,  0.4960,  2.0425,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.2295,  0.7226, -0.2248,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000, -0.7340,  0.4048, -0.4633,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.5439, -1.1635, -0.1171,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  1.0175,  0.2902, -0.7933,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]

In [33]:
# conv 2d + padding
images = torch.randn(size=(1, 3, 28, 28))

conv = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, padding='same')
y = conv(images)
print(images.size())
print(y.size())

torch.Size([1, 3, 28, 28])
torch.Size([1, 1, 28, 28])


In [36]:
# stride + conv2d


images = torch.randn(size=(1, 3, 28, 28))
print('image size: ', images.size())

convs = nn.Conv2d(in_channels=3, out_channels=1, kernel_size= 3 , padding='valid', stride=2)
cv = convs(images)
print('output size: ', cv.size())

image size:  torch.Size([1, 3, 28, 28])
output size:  torch.Size([1, 1, 13, 13])


In [37]:
# stride + pooling 
images = torch.randn(size=(1, 3, 28, 28))
print('image size: ', images.size())

pool = nn.MaxPool2d(kernel_size=3, stride=2)
cv = pool(images)
print('output size: ', cv.size())


image size:  torch.Size([1, 3, 28, 28])
output size:  torch.Size([1, 3, 13, 13])
